const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {Client,validateUrl}=require('../dist/providers');const {safePath,canWrite}=require('../dist/policy');
test('URLs accept remote HTTP and reject credentials and parameters',()=>{for(const url of ['https://u:p@example.com','https://example.com?key=secret','file:///tmp'])assert.throws(()=>validateUrl(url));assert.equal(validateUrl('http://localhost:11434/'),'http://localhost:11434');assert.equal(validateUrl('http://10.0.0.5:8080/v1'),'http://10.0.0.5:8080/v1');assert.equal(validateUrl('http://example.com/v1'),'http://example.com/v1');});
test('read-only modes cannot write',()=>{assert.equal(canWrite('ask'),false);assert.equal(canWrite('plan'),false);assert.equal(canWrite('agent'),true);});
test('workspace boundaries reject traversal and symlinks',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-test-'));try{await fs.symlink(os.tmpdir(),path.join(root,'outside'));for(const name of ['../escape','/tmp/file','.env','.git/config','outside/escaped.txt'])await assert.rejects(safePath(root,name));assert.equal(await safePath(root,'src/new.ts'),path.join(await fs.realpath(root),'src/new.ts'));}finally{await fs.rm(root,{recursive:true,force:true});}});
test('provider catalogs normalize all five APIs and keep keys in headers',async()=>{for(const kind of ['openai','compatible','anthropic','gemini','ollama']){let request;const client=new Client({id:'1',name:kind,kind,baseUrl:'https://example.com'},'private-key',async(url,options)=>{request={url,options};return new Response(JSON.stringify(kind==='ollama'?{models:[{name:'local'}]}:kind==='gemini'?{models:[{name:'models/chat',supportedGenerationMethods:['generateContent']},{name:'models/embed',supportedGenerationMethods:['embedContent']}]}:{data:[{id:'chat'}]}));});assert.deepEqual(await client.models(),[kind==='ollama'?'local':'chat']);assert.ok(!request.url.includes('private-key'));assert.equal(request.options.redirect,'manual');}});
test('Gemini pagination retains chat models',async()=>{let n=0;const client=new Client({id:'1',name:'G',kind:'gemini',baseUrl:'https://example.com'},'key',async()=>new Response(JSON.stringify(++n===1?{models:[{name:'models/a',supportedGenerationMethods:['generateContent']}],nextPageToken:'next'}:{models:[{name:'models/b',supportedGenerationMethods:['generateContent']}]})));assert.deepEqual(await client.models(),['a','b']);});
test('errors do not expose provider bodies or secrets',async()=>{const client=new Client({id:'1',name:'OpenAI',kind:'openai',baseUrl:'https://example.com'},'secret',async()=>new Response('secret',{status:401}));await assert.rejects(client.models(),e=>e.message.includes('401')&&!e.message.includes('secret'));});
test('all chat adapters extract generated text',async()=>{for(const kind of ['openai','compatible','anthropic','gemini','ollama']){const body=kind==='anthropic'?{content:[{type:'text',text:'ok'}]}:kind==='gemini'?{candidates:[{content:{parts:[{text:'ok'}]}}]}:kind==='ollama'?{message:{content:'ok'}}:{choices:[{message:{content:'ok'}}]};const client=new Client({id:'1',name:kind,kind,baseUrl:'https://example.com'},'key',async()=>new Response(JSON.stringify(body)));assert.equal(await client.chat('model','system',[{role:'user',content:'hello'}],new AbortController().signal),'ok');}});
