const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');
const {readStream}=require('../dist/providers/stream');const {decodeNative}=require('../dist/core/native');const {reviewPatch,selectHunks}=require('../dist/tools/hunks');const {ChangeStore}=require('../dist/tools/changes');const {snapshotTree}=require('../dist/policy/sandbox');const {projectRules}=require('../dist/context/projectContext');
function response(events,kind='openai'){const wire=events.map(e=>kind==='ollama'?JSON.stringify(e)+'\n':'data: '+JSON.stringify(e)+'\n\n').join('');const bytes=new TextEncoder().encode(wire);return new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=3)c.enqueue(bytes.slice(i,i+3));c.close();}}));}
test('stream indexes are bounded before allocating tool blocks',async()=>{
 await assert.rejects(readStream(response([{choices:[{delta:{tool_calls:[{index:1e9,function:{name:'read_file'}}]}}]}]),'openai',new AbortController().signal,()=>{}),/index/);
 await assert.rejects(readStream(response([{type:'content_block_start',index:-1,content_block:{type:'text'}}]),'anthropic',new AbortController().signal,()=>{}),/index/);
});
test('streaming accumulates split native arguments and UTF-8 before decoding',async()=>{let text='';const raw=await readStream(response([{choices:[{delta:{content:'Olá ',tool_calls:[{index:0,id:'a',function:{name:'read_file',arguments:'{"pa'}}]}}]},{choices:[{delta:{content:'mundo',tool_calls:[{index:0,function:{arguments:'th":"a"}'}}]},finish_reason:'tool_calls'}]}]),'openai',new AbortController().signal,s=>text+=s);assert.equal(text,'Olá mundo');assert.equal(decodeNative('openai',raw).calls[0].arguments.path,'a');});
test('truncated stream fails without producing an executable call',async()=>{await assert.rejects(readStream(response([{choices:[{delta:{tool_calls:[{index:0,id:'a',function:{name:'write_file',arguments:'{}'}}]}}]}]),'openai',new AbortController().signal,()=>{}),/before completion/);});
test('Anthropic stream preserves signed thinking without rendering it',async()=>{let text='';const raw=await readStream(response([{type:'content_block_start',index:0,content_block:{type:'thinking',thinking:''}},{type:'content_block_delta',index:0,delta:{type:'thinking_delta',thinking:'private'}},{type:'content_block_delta',index:0,delta:{type:'signature_delta',signature:'signature'}},{type:'content_block_start',index:1,content_block:{type:'text',text:''}},{type:'content_block_delta',index:1,delta:{type:'text_delta',text:'answer'}},{type:'message_delta',delta:{stop_reason:'end_turn'}},{type:'message_stop'}]),'anthropic',new AbortController().signal,s=>text+=s);assert.equal(text,'answer');assert.equal(decodeNative('anthropic',raw).continuation[0].signature,'signature');});
test('Ollama and Gemini streams produce complete final text',async()=>{for(const kind of ['ollama','gemini']){const events=kind==='ollama'?[{message:{content:'hello'}},{done:true,message:{content:''}}]:[{candidates:[{content:{parts:[{text:'hello'}]},finishReason:'STOP'}]}];const raw=await readStream(response(events,kind),kind,new AbortController().signal,()=>{});assert.equal(decodeNative(kind,raw).text,'hello');}});
test('partial hunk approval applies only selected changes',()=>{const before=Array.from({length:30},(_,i)=>'line '+i).join('\n');const after=before.replace('line 1\n','changed 1\n').replace('line 25\n','changed 25\n');const patch=reviewPatch(before,after);assert.equal(patch.hunks.length,2);const selected=selectHunks(before,patch,[0]);assert.ok(selected.includes('changed 1'));assert.ok(!selected.includes('changed 25'));assert.equal(selectHunks(before,patch,[]),before);assert.equal(selectHunks(before,patch,[0,1]),after);});
test('change journal survives restart and records partial approval content',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-journal-'));try{const store=new ChangeStore(dir),id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';const row=await store.propose(id,'a','before','after');await store.replaceProposal(id,row.id,'partial');await store.mark(id,row.id,'applied');const loaded=await new ChangeStore(dir).list(id);assert.equal(loaded[0].after,'partial');assert.equal(loaded[0].status,'applied');await assert.rejects(store.propose('../x','a',null,'x'));}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('sandbox snapshots omit credentials, binaries and escaping symlinks',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-snapshot-'));try{await fs.writeFile(path.join(dir,'a.ts'),'ok');await fs.writeFile(path.join(dir,'.env'),'secret');await fs.writeFile(path.join(dir,'key.pem'),'secret');await fs.writeFile(path.join(dir,'binary'),Buffer.from([0,1]));await fs.symlink(os.tmpdir(),path.join(dir,'escape'));const files=await snapshotTree(dir);assert.deepEqual([...files.keys()],['a.ts']);}finally{await fs.rm(dir,{recursive:true,force:true});}});
test('project rules load root then scoped instructions',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-rules-'));try{await fs.mkdir(path.join(dir,'src'));await fs.writeFile(path.join(dir,'AGENTS.md'),'root');await fs.writeFile(path.join(dir,'src/AGENTS.md'),'specific');const rules=await projectRules(dir,['src/a.ts']);assert.deepEqual(rules.map(r=>r.text),['root','specific']);}finally{await fs.rm(dir,{recursive:true,force:true});}});

test('session migration preserves IDs and does not resurrect deleted sessions',async()=>{
 const {SessionStore}=require('../dist/session/sessions');const dir=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-migrate-'));
 try{const old=new SessionStore(path.join(dir,'old'));const session=old.create('legacy','ask',{providerId:'p',modelId:'m'});await old.save(session);
 const next=new SessionStore(path.join(dir,'new'),path.join(dir,'old'),'/workspace');assert.equal((await next.load(session.id)).root,'/workspace');await next.remove(session.id);
 const reopened=new SessionStore(path.join(dir,'new'),path.join(dir,'old'),'/workspace');assert.deepEqual(await reopened.list(),[]);
 }finally{await fs.rm(dir,{recursive:true,force:true});}
});
