const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {ProviderManager}=require('../dist/providers/providerManager');const {probeModel}=require('../dist/providers/modelProbe');const {runIsolated}=require('../dist/providers/isolatedRun');const {ExecutionError}=require('../dist/core/execution');const {SessionStore}=require('../dist/session/sessions');const {ToolOutputs}=require('../dist/tools/toolOutputs');
const model={providerId:'p',modelId:'m'};
function manager(kind,transport,extra={}){const values={providers:[{id:'p',name:'Fixture',kind,baseUrl:'http://fixture.test'}],modelPreferences:extra};return new ProviderManager({get:(k,d)=>values[k]??d,update:async(k,v)=>{values[k]=v;}},{get:async()=>'',store:async()=>{},delete:async()=>{}},transport);}
const json=v=>new Response(JSON.stringify(v),{headers:{'content-type':'application/json'}});
function wire(kind,text,tool){const c={id:'probe-call',name:'read_file',arguments:{path:'vortex-connection-probe.txt'}};return kind==='anthropic'?{content:tool?[{type:'tool_use',id:c.id,name:c.name,input:c.arguments}]:[{type:'text',text}]}:kind==='gemini'?{candidates:[{content:{parts:tool?[{functionCall:{id:c.id,name:c.name,args:c.arguments}}]:[{text}]}}]}:kind==='ollama'?{message:tool?{content:'',tool_calls:[{id:c.id,function:{name:c.name,arguments:c.arguments}}]}:{content:text},done:true,done_reason:'stop'}:{choices:[{finish_reason:'stop',message:tool?{content:null,tool_calls:[{id:c.id,type:'function',function:{name:c.name,arguments:JSON.stringify(c.arguments)}}]}:{content:text}}]};}
for(const kind of ['openai','compatible','anthropic','gemini','ollama'])test(kind+' tool probe uses shared runtime and verifies result in final answer',async()=>{
 let rounds=0;const provider=manager(kind,async(_url,options)=>{const body=JSON.parse(options?.body||'{}');if(!body.messages&&!body.contents)return json({context_length:16384});rounds++;const code=JSON.stringify(body).match(/Verification code: ([a-f0-9-]{36})/)?.[1];return json(wire(kind,code?'Verified '+code:'',!code));});
 const result=await probeModel(provider,model,new AbortController().signal);assert.equal(result.tools,'validated');assert.equal(result.chat,'validated');assert.equal(result.streaming,'unverified');assert.equal(rounds,2);assert.equal(result.protocol,'native');
});
test('probe rejects a plain answer that never executed a tool',async()=>{const p=manager('compatible',async()=>json(wire('compatible','OK',false)));const r=await probeModel(p,model,new AbortController().signal);assert.equal(r.tools,'failed');});
test('compatibility probe uses textual actions and validates the returned nonce',async()=>{const p=manager('compatible',async(_url,options)=>{const body=JSON.stringify(JSON.parse(options?.body||'{}')),code=body.match(/Verification code: ([a-f0-9-]{36})/)?.[1];return json(wire('compatible',code?JSON.stringify({action:'finish',text:code}):JSON.stringify({action:'read_file',path:'vortex-connection-probe.txt'}),false));},{toolProtocols:{[JSON.stringify(['p','m'])]:'compatibility'}});const result=await probeModel(p,model,new AbortController().signal);assert.equal(result.tools,'validated');assert.equal(result.protocol,'compatibility');});
test('runtime stops on typed command timeout and retains an uncertain operation',async()=>{let rounds=0;const p=manager('compatible',async()=>{rounds++;return json({choices:[{message:{tool_calls:[{id:'cmd',function:{name:'run_command',arguments:JSON.stringify({command:'fixture'})}}]}}]});});p.ensureLimits=async()=>{};const result=await runIsolated(p,model,'Run the requested fixture command','agent',async()=>{throw new ExecutionError('command_timeout','Timed out with partial output.');},new AbortController().signal);assert.equal(rounds,1);assert.equal(result.session.runState,'paused');assert.equal(result.session.pendingTool.name,'run_command');assert.equal(result.events.find(e=>e.type==='runFailure').retryable,false);assert.match(result.session.messages.at(-1).toolResult.output,/uncertain/);});
test('saved output pages survive a new output store',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-output-'));try{const first=new ToolOutputs(root),preview=JSON.parse(first.preserve('A'.repeat(5000)+'END',30));await first.flush();const second=new ToolOutputs(root);await second.restore();assert.equal(JSON.parse(second.read(preview.output_id,5000)).text,'END');}finally{await fs.rm(root,{recursive:true,force:true});}});
test('session lease prevents a second writer and revisions reject stale resumes',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-lease-'));try{const a=new SessionStore(root),b=new SessionStore(root),s=a.create('Task','ask',model);await a.save(s);const stale=await b.load(s.id),release=await a.begin(s);await assert.rejects(b.begin(stale),/another window/);s.title='Updated';await a.save(s);await release();await assert.rejects(b.begin(stale),/changed in another window/);const fresh=await b.load(s.id),end=await b.begin(fresh);await end();}finally{await fs.rm(root,{recursive:true,force:true});}});
test('deleting a session removes associated data and matching trace, never workspace files',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-delete-'));try{const trace=path.join(root,'last-flow.json'),store=new SessionStore(path.join(root,'sessions'),undefined,undefined,root,trace),s=store.create('Task','ask',model);await store.save(s);await fs.mkdir(path.join(root,'changes'));await fs.writeFile(path.join(root,'changes',s.id+'.changes.json'),'[]');await fs.mkdir(path.join(root,'artifacts',s.id),{recursive:true});await fs.writeFile(trace,JSON.stringify({conversation_id:s.id}));await fs.writeFile(path.join(root,'user-file'),'keep');await store.remove(s.id);assert.equal(await fs.readFile(path.join(root,'user-file'),'utf8'),'keep');for(const file of [trace,path.join(root,'artifacts',s.id),path.join(root,'changes',s.id+'.changes.json')])await assert.rejects(fs.stat(file),e=>e.code==='ENOENT');assert.equal((await store.list()).length,0);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('response budget defaults remain stable and explicit model budget is validated',async()=>{const p=manager('compatible',async()=>json({}));assert.equal(p.contextBudget(model).output,4096);let prefs=p.preferences();await p.saveModels({...prefs,outputTokens:{[JSON.stringify(['p','m'])]:8000}});assert.equal(p.contextBudget(model).output,8000);prefs=p.preferences();await assert.rejects(p.saveModels({...prefs,outputTokens:{[JSON.stringify(['p','m'])]:20000}}),/exceeds/);assert.equal(p.preferences().storage.retentionDays,0);});

test('automatic retention preserves unfinished sessions and manual default preserves everything',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-retention-'));try{const store=new SessionStore(root);const complete=store.create('Done','ask',model),paused=store.create('Pending','ask',model);complete.runState='complete';paused.runState='paused';await store.save(complete);await store.save(paused);for(const session of [complete,paused]){const file=path.join(root,session.id+'.json'),data=JSON.parse(await fs.readFile(file,'utf8'));data.updatedAt=Date.now()-100*86400000;await fs.writeFile(file,JSON.stringify(data));}assert.equal(await store.cleanup(0),0);assert.equal((await store.list()).length,2);assert.equal(await store.cleanup(90),1);assert.equal((await store.list())[0].id,paused.id);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('interrupted deletion resumes and expired output IDs fail explicitly',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-recovery-'));try{const store=new SessionStore(root),session=store.create('Delete','ask',model);await store.save(session);await fs.writeFile(path.join(root,session.id+'.deleting'),'1');await store.recoverDeletions();assert.equal((await store.list()).length,0);const pages=new ToolOutputs();assert.throws(()=>pages.read('expired'),/preview was partial/);}finally{await fs.rm(root,{recursive:true,force:true});}});
test('current-turn compaction preserves the current request and latest tool result',async()=>{let count=0,summaries=0,lastRequest;const p=manager('compatible',async(_url,options)=>{const body=JSON.parse(options.body||'{}');if(body.messages?.[0]?.content.startsWith('Summarize task evidence')){summaries++;return json(wire('compatible','Evidence from read-1 and read-2 retained. No changes applied.',false));}count++;lastRequest=body;return json(count<=3?{choices:[{message:{tool_calls:[{id:'read-'+count,function:{name:'read_file',arguments:JSON.stringify({path:'file-'+count})}}]}}]}:wire('compatible','Inspected the three requested files.',false));});p.ensureLimits=async()=>{};p.contextBudget=()=>({tokens:7500,output:512,source:'custom'});const result=await runIsolated(p,model,'Inspect three files and summarize the evidence','ask',async a=>'Result '+a.path+' '+('evidence '.repeat(650)),new AbortController().signal);assert.equal(result.session.runState,'complete',JSON.stringify(result.events.filter(e=>e.type==='runFailure')));assert.ok(summaries>0);assert.match(JSON.stringify(lastRequest),/Inspect three files/);assert.match(JSON.stringify(lastRequest),/file-3/);assert.equal(result.session.messages.filter(m=>m.toolResult).length,3);});
test('browser message boundary rejects malformed activities, state and output',()=>{const esbuild=require('esbuild'),Module=require('node:module');const build=esbuild.buildSync({entryPoints:[path.join(__dirname,'../webview/messages.ts')],bundle:true,platform:'node',format:'cjs',write:false});const module=new Module('message-fixture');module._compile(build.outputFiles[0].text,'message-fixture.cjs');const {isHostResponse}=module.exports;assert.equal(isHostResponse({type:'activityUpdate',activity:{id:'x'}}),false);assert.equal(isHostResponse({type:'commandOutput',runId:'r',id:'t',stream:'stdout',text:'ok'}),true);assert.equal(isHostResponse({type:'commandOutput',runId:'r',id:'t',stream:'stdout',text:'x'.repeat(40000)}),false);assert.equal(isHostResponse({type:'state',state:{preferences:{}},busy:false}),false);});

test('only one contender can reclaim a lock from a confirmed dead process',async()=>{const {execFile}=require('node:child_process');const {acquireSessionLock,sessionLockActive}=require('../dist/session/sessionLock');const pid=await new Promise((resolve,reject)=>execFile(process.execPath,['-e','process.stdout.write(String(process.pid))'],(e,out)=>e?reject(e):resolve(Number(out))));const root=await fs.mkdtemp(path.join(os.tmpdir(),'vortex-dead-'));let release;try{const lock=path.join(root,'session.lock');await fs.mkdir(lock);await fs.writeFile(path.join(lock,'11111111-1111-1111-1111-111111111111.json'),JSON.stringify({pid}));const attempts=await Promise.allSettled([acquireSessionLock(lock),acquireSessionLock(lock)]);const successful=attempts.filter(r=>r.status==='fulfilled');assert.equal(successful.length,1);release=successful[0].value;assert.equal(await sessionLockActive(lock),true);}finally{await release?.();await fs.rm(root,{recursive:true,force:true});}});

test('run completion is announced only after the session lease has been released',async()=>{
 const {AgentRuntime}=require('../dist/core/agentRuntime');const {randomUUID}=require('node:crypto');let leased=false,released=false,completed=false;
 const p=manager('compatible',async()=>json(wire('compatible','Hello!',false)));p.ensureLimits=async()=>{};
 const store={create:()=>({id:randomUUID(),title:'Hello',updatedAt:Date.now(),events:[],messages:[],checklist:[],mode:'ask',permission:'supervised',model}),begin:async()=>{leased=true;return async()=>{await new Promise(r=>setTimeout(r,20));leased=false;released=true;};},save:async()=>{}};
 const host={trusted:()=>true,roots:()=>[],pickRoot:async()=>undefined,choosePermission:async()=>undefined,confirmUncertain:async()=>false,execute:async()=>{throw new Error('No tool expected');}};
 const runtime=new AgentRuntime(p,event=>{if(event.type==='runEnd'){assert.equal(leased,false);assert.equal(released,true);completed=true;}},store,undefined,undefined,undefined,undefined,host);
 try{await runtime.start({type:'start',requestId:randomUUID(),prompt:'Hello',mode:'ask',permission:'supervised',model});assert.equal(completed,true);}finally{runtime.dispose();}
});
